{
 "title": "Influxdb",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "INSIDE",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT * FROM \"withLocation\" WHERE \"location\" IN ('Raspberry')\r\n"
    }
   ]
  },
  {
   "title": "Temperature Bar",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time,raspberry_temp,arduino_temp FROM \"withoutLocation\""
    }
   ]
  },
  {
   "title": "Humidity Bar",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time,raspberry_humidity,arduino_humidity FROM \"withoutLocation\""
    }
   ]
  },
  {
   "title": "OUTSIDE",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT * FROM \"withLocation\" WHERE \"location\" IN ('Arduino')\r\n"
    }
   ]
  },
  {
   "title": "Bad Air Quality Bar",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time,raspberry_air_quality,arduino_air_quality FROM \"withoutLocation\""
    }
   ]
  },
  {
   "title": "Temp Time Table",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time,raspberry_temp,arduino_temp FROM \"withoutLocation\""
    }
   ]
  },
  {
   "title": "HumidityTime Table",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time,raspberry_humidity,arduino_humidity FROM \"withoutLocation\""
    }
   ]
  }
 ]
}